# Generated by Django 4.2.6 on 2024-07-06 08:51

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=15)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_applied'],
            },
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=40)),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address', models.CharField(max_length=100)),
                ('linked_in', models.URLField(blank=True, null=True)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Candidate/photo')),
                ('about', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=100)),
                ('issuing_organization', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='media/certifications/')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('education_status', models.CharField(choices=[('highschool', 'High School'), ('Certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor-degree', "Bachelor's degree"), ('Master-degree', "Master's Degree"), ('doctorate', 'Doctorate'), ('other', 'Other')], max_length=40)),
                ('field_of_study', models.CharField(max_length=40)),
                ('education_period_start', models.DateField()),
                ('education_period_end', models.DateField()),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='media/educationDocument')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('work_time_line_start', models.DateField()),
                ('work_time_line_end', models.DateField()),
                ('job_title', models.CharField(max_length=50)),
                ('reference_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('reference_name', models.CharField(max_length=40)),
                ('reference_email', models.CharField(max_length=40)),
                ('reference_job_title', models.CharField(max_length=40)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_schedule', models.DateField(blank=True, null=True)),
                ('time_schedule', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=15, null=True)),
                ('type', models.CharField(blank=True, choices=[('phone', 'Phone'), ('in-person', 'In-Person'), ('video', 'Video')], max_length=15, null=True)),
                ('note', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=600, null=True, unique=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date_schedule'],
            },
        ),
        migrations.CreateModel(
            name='Job_Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', froala_editor.fields.FroalaField()),
                ('vacancies', models.IntegerField()),
                ('experience', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Ērer Sātā', 'Ērer Sātā'), ('Shashemenē', 'Shashemenē'), ('K’ebrī Dehar', 'K’ebrī Dehar'), ('Nazrēt', 'Nazrēt'), ('Mekele', 'Mekele'), ('Godē', 'Godē'), ('Āwasa', 'Āwasa'), ('Dire Dawa', 'Dire Dawa'), ('Bahir Dar', 'Bahir Dar'), ('Sodo', 'Sodo'), ('Ārba Minch’', 'Ārba Minch’'), ('Desē', 'Desē'), ('Hosa’ina', 'Hosa’ina'), ('K’ebrī Beyah', 'K’ebrī Beyah'), ('Jijiga', 'Jijiga'), ('Dīla', 'Dīla'), ('Nek’emtē', 'Nek’emtē'), ('Debre Birhan', 'Debre Birhan'), ('Debre Mark’os', 'Debre Mark’os'), ('Ferfer', 'Ferfer'), ('Āwarē', 'Āwarē'), ('Harar', 'Harar'), ('Kombolcha', 'Kombolcha'), ('Jīma', 'Jīma'), ('Debre Tabor', 'Debre Tabor'), ('Harshin', 'Harshin'), ('Ādīgrat', 'Ādīgrat'), ('Debre Zeyit', 'Debre Zeyit'), ('Gambēla', 'Gambēla'), ('Mīzan Teferī', 'Mīzan Teferī'), ('Ādwa', 'Ādwa'), ('Gonder', 'Gonder'), ('Bodītī', 'Bodītī'), ('Āsela', 'Āsela'), ('Āksum', 'Āksum'), ('Bonga', 'Bonga'), ('Finote Selam', 'Finote Selam'), ('Semera', 'Semera'), ('Goba', 'Goba'), ('Hāgere Hiywet', 'Hāgere Hiywet'), ('Robē', 'Robē'), ('Yirga ‘Alem', 'Yirga ‘Alem'), ('Giyon', 'Giyon'), ('Bedēsa', 'Bedēsa'), ('Āzezo', 'Āzezo'), ('Butajīra', 'Butajīra'), ('Ālamat’ā', 'Ālamat’ā'), ('Āreka', 'Āreka'), ('Gīmbī', 'Gīmbī'), ('Wik’ro', 'Wik’ro'), ('Welk’īt’ē', 'Welk’īt’ē'), ('Metu', 'Metu'), ('Fichē', 'Fichē'), ('K’olīto', 'K’olīto'), ('Genet', 'Genet'), ('Āgaro', 'Āgaro'), ('Gelemso', 'Gelemso'), ('Āsosa', 'Āsosa')], default=True, max_length=100)),
                ('salary_range_start', models.FloatField()),
                ('salary_range_final', models.FloatField()),
                ('type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('seasonal ', 'seasonal'), ('contract', 'Contract'), ('remote', 'Remote')], max_length=30)),
                ('compensation_type', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('hourly', 'Hourly'), ('commission', 'Commission'), ('bonus', 'Bonus'), ('benefits', 'Benefits')], max_length=30, null=True)),
                ('job_status', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_closed', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('proficient', models.CharField(choices=[('basic', 'Basic'), ('limited_working_proficiency', 'Limited Working Proficiency'), ('professional_working_proficiency', 'Professional Working Proficiency'), ('native_proficiency', 'Native Proficiency')], max_length=40)),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=40)),
                ('detail', froala_editor.fields.FroalaField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('validable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobPortal.candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobPortal.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.choice')),
                ('for_skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.skill')),
            ],
        ),
    ]
