# Generated by Django 5.0.4 on 2024-04-22 08:21

import django.db.models.deletion
import froala_editor.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In review'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=15)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_applied'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('education_status', models.CharField(choices=[('highschool', 'High School'), ('Certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor-degree', "Bachelor's degree"), ('Master-degree', "Master's Degree"), ('doctorate', 'Doctorate'), ('other', 'Other')], max_length=40)),
                ('field_of_study', models.CharField(max_length=40)),
                ('education_period_start', models.DateField()),
                ('education_period_end', models.DateField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('work_time_line_start', models.DateField()),
                ('work_time_line_end', models.DateField()),
                ('job_title', models.CharField(max_length=50)),
                ('reference_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('reference_name', models.CharField(max_length=40)),
                ('reference_email', models.CharField(max_length=40)),
                ('reference_job_title', models.CharField(max_length=40)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_schedule', models.DateField(blank=True, null=True)),
                ('time_schedule', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=15, null=True)),
                ('interview_type', models.CharField(blank=True, choices=[('phone', 'Phone'), ('in-person', 'In-Person')], max_length=15, null=True)),
                ('note', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=600, null=True, unique=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JobPortal.application')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_schedule'],
            },
        ),
        migrations.CreateModel(
            name='Job_Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', froala_editor.fields.FroalaField()),
                ('vacancies', models.IntegerField()),
                ('experience', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('salary_range_start', models.FloatField()),
                ('salary_range_final', models.FloatField()),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('seasonal ', 'seasonal'), ('contract', 'Contract'), ('remote', 'Remote')], max_length=30)),
                ('job_status', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_closed', models.DateField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Company.company')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.sector')),
                ('skills', models.ManyToManyField(to='JobPortal.skill')),
            ],
            options={
                'ordering': ['-date_posted', '-date_closed'],
            },
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobPortal.job_posting')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.job_posting'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('skill', models.ManyToManyField(to='JobPortal.skill')),
            ],
        ),
    ]
