# Generated by Django 4.2.3 on 2024-04-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('JobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.company'),
        ),
    ]
