# Generated by Django 4.2.3 on 2024-05-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='skill',
            field=models.ManyToManyField(null=True, to='JobPortal.skill'),
        ),
    ]
