# Generated by Django 4.2.3 on 2024-05-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='covert_letter',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
