# Generated by Django 4.2.3 on 2024-05-13 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0002_application_covert_letter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='covert_letter',
            new_name='cover_letter',
        ),
    ]
