# Generated by Django 4.2.3 on 2024-05-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0002_candidate_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='skill',
            field=models.ManyToManyField(to='JobPortal.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='validable',
            field=models.BooleanField(default=False),
        ),
    ]
