# Generated by Django 4.2.3 on 2024-04-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0002_job_posting_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='compensation_type',
            field=models.CharField(blank=True, choices=[('salary', 'Salary'), ('hourly', 'Hourly'), ('commission', 'Commission'), ('bonus', 'Bonus'), ('benefits', 'Benefits')], max_length=30, null=True),
        ),
    ]
