# Generated by Django 4.2.3 on 2024-05-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0003_rename_covert_letter_application_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
