# Generated by Django 4.2.3 on 2024-05-13 06:53

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0004_alter_application_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
