# Generated by Django 4.2.3 on 2024-05-10 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0004_remove_question_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='for_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.userskill'),
        ),
    ]
