# Generated by Django 4.2.3 on 2024-04-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0004_alter_job_posting_compensation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_posting',
            name='date_closed',
            field=models.DateTimeField(),
        ),
    ]
