# Generated by Django 4.2.3 on 2024-04-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0005_alter_job_posting_date_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='about',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_name',
        ),
    ]
