# Generated by Django 4.2.3 on 2024-05-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0005_alter_application_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
