# Generated by Django 4.2.3 on 2024-04-27 11:26

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0006_remove_candidate_about_remove_candidate_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
