# Generated by Django 4.2.3 on 2024-05-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0007_remove_application_read_job_posting_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
