# Generated by Django 4.2.3 on 2024-04-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0007_alter_candidate_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='git_hub',
        ),
    ]
