# Generated by Django 4.2.3 on 2024-05-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0008_application_read_alter_language_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='slug',
        ),
    ]
