# Generated by Django 4.2.3 on 2024-05-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0008_alter_question_for_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
