# Generated by Django 4.2.3 on 2024-05-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0008_alter_question_for_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='validated',
            field=models.BooleanField(default=True),
        ),
    ]
