# Generated by Django 4.2.3 on 2024-05-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0008_application_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
