# Generated by Django 4.2.3 on 2024-05-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0009_alter_userskill_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_latter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviews',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
