<<<<<<<< HEAD:JobPortal/migrations/0010_application_cover_latter_interviews_read.py
# Generated by Django 4.2.3 on 2024-05-12 12:08
========
# Generated by Django 4.2.3 on 2024-05-13 08:17
>>>>>>>> 446164a0ec5e0fbe5fe01f0e438dbd542fff7181:Company/migrations/0011_company_read.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<<< HEAD:JobPortal/migrations/0010_application_cover_latter_interviews_read.py
        ('JobPortal', '0009_alter_userskill_validated'),
========
        ('Company', '0010_remove_company_location'),
>>>>>>>> 446164a0ec5e0fbe5fe01f0e438dbd542fff7181:Company/migrations/0011_company_read.py
    ]

    operations = [
        migrations.AddField(
<<<<<<<< HEAD:JobPortal/migrations/0010_application_cover_latter_interviews_read.py
            model_name='application',
            name='cover_latter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviews',
========
            model_name='company',
>>>>>>>> 446164a0ec5e0fbe5fe01f0e438dbd542fff7181:Company/migrations/0011_company_read.py
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
