# Generated by Django 4.2.3 on 2024-05-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0009_remove_candidate_resume_candidate_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=15),
        ),
    ]
