# Generated by Django 4.2.6 on 2024-07-04 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobPortal', '0009_remove_language_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='education/documents/'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=100)),
                ('issuing_organization', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='certifications/documents/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
