# Generated by Django 4.2.3 on 2024-05-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0010_application_cover_latter_interviews_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cover_latter',
            new_name='cover_letter',
        ),
    ]
