# Generated by Django 4.2.6 on 2024-07-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0010_education_document_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/certifications/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/educationDocument'),
        ),
    ]
