# Generated by Django 4.2.3 on 2024-05-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0011_rename_cover_latter_application_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='city',
            field=models.CharField(default='Addis Ababa', max_length=100),
        ),
    ]
