# Generated by Django 4.2.3 on 2024-05-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0012_job_posting_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_posting',
            name='city',
            field=models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Ērer Sātā', 'Ērer Sātā'), ('Shashemenē', 'Shashemenē'), ('K’ebrī Dehar', 'K’ebrī Dehar'), ('Nazrēt', 'Nazrēt'), ('Mekele', 'Mekele'), ('Godē', 'Godē'), ('Āwasa', 'Āwasa'), ('Dire Dawa', 'Dire Dawa'), ('Bahir Dar', 'Bahir Dar'), ('Sodo', 'Sodo'), ('Ārba Minch’', 'Ārba Minch’'), ('Desē', 'Desē'), ('Hosa’ina', 'Hosa’ina'), ('K’ebrī Beyah', 'K’ebrī Beyah'), ('Jijiga', 'Jijiga'), ('Dīla', 'Dīla'), ('Nek’emtē', 'Nek’emtē'), ('Debre Birhan', 'Debre Birhan'), ('Debre Mark’os', 'Debre Mark’os'), ('Ferfer', 'Ferfer'), ('Āwarē', 'Āwarē'), ('Harar', 'Harar'), ('Kombolcha', 'Kombolcha'), ('Jīma', 'Jīma'), ('Debre Tabor', 'Debre Tabor'), ('Harshin', 'Harshin'), ('Ādīgrat', 'Ādīgrat'), ('Debre Zeyit', 'Debre Zeyit'), ('Gambēla', 'Gambēla'), ('Mīzan Teferī', 'Mīzan Teferī'), ('Ādwa', 'Ādwa'), ('Gonder', 'Gonder'), ('Bodītī', 'Bodītī'), ('Āsela', 'Āsela'), ('Āksum', 'Āksum'), ('Bonga', 'Bonga'), ('Finote Selam', 'Finote Selam'), ('Semera', 'Semera'), ('Goba', 'Goba'), ('Hāgere Hiywet', 'Hāgere Hiywet'), ('Robē', 'Robē'), ('Yirga ‘Alem', 'Yirga ‘Alem'), ('Giyon', 'Giyon'), ('Bedēsa', 'Bedēsa'), ('Āzezo', 'Āzezo'), ('Butajīra', 'Butajīra'), ('Ālamat’ā', 'Ālamat’ā'), ('Āreka', 'Āreka'), ('Gīmbī', 'Gīmbī'), ('Wik’ro', 'Wik’ro'), ('Welk’īt’ē', 'Welk’īt’ē'), ('Metu', 'Metu'), ('Fichē', 'Fichē'), ('K’olīto', 'K’olīto'), ('Genet', 'Genet'), ('Āgaro', 'Āgaro'), ('Gelemso', 'Gelemso'), ('Āsosa', 'Āsosa')], default=True, max_length=100),
        ),
    ]
