# Generated by Django 4.2.3 on 2024-05-03 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0012_alter_interviews_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JobPortal.application'),
        ),
    ]
