# Generated by Django 4.2.3 on 2024-05-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0016_alter_interviews_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job_posting',
            options={'ordering': ['sector', '-date_posted', '-date_closed']},
        ),
    ]
