# Generated by Django 4.2.3 on 2024-05-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0017_alter_job_posting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job_posting',
            options={'ordering': ['-date_posted']},
        ),
    ]
