# Generated by Django 4.2.3 on 2024-05-09 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0018_alter_job_posting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=15)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.choice')),
                ('for_skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.skill')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='for_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.question'),
        ),
    ]
