# Generated by Django 4.2.3 on 2024-05-09 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobPortal', '0018_alter_job_posting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, unique=True)),
                ('proficient', models.CharField(choices=[('basic', 'Basic'), ('limited_working_proficiency', 'Limited Working Proficiency'), ('professional_working_proficiency', 'Professional Working Proficiency'), ('native_proficiency', 'Native Proficiency')], max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=40)),
                ('detail', froala_editor.fields.FroalaField()),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
