# Generated by Django 4.2.3 on 2024-05-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0019_choice_question_choice_for_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='validable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobPortal.candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobPortal.skill')),
            ],
        ),
    ]
