# Generated by Django 5.0.4 on 2024-04-24 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='company/logo'),
            preserve_default=False,
        ),
    ]
