# Generated by Django 4.2.3 on 2024-04-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_alter_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
