# Generated by Django 4.2.3 on 2024-04-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_alter_blog_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
