# Generated by Django 4.2.3 on 2024-04-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_contact_message_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_message',
            options={'ordering': ['-created_at']},
        ),
    ]
