# Generated by Django 4.2.3 on 2024-05-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_company_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
