# Generated by Django 4.2.3 on 2024-05-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0010_remove_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
